### ISSUE TITLE
doesn't work with expo

### ISSUE THREAD

**Issue by HardMode2015** [siposdani87/expo-maps-polygon-editor#1]
i try use package in expo doesn't work with me

  "expo": "~47.0.12",
  "react-native": "0.70.5",
  "react-native-maps": "1.3.2",

stack screen

anyway to use it with expo

thank you

**Comment by siposdani87** [comment]
Hi! If you use with sdk47 of expo, you can install the v0.6.0 of expo-maps-polygon-editor. For more help to see the example directory and check the correct package versions.

**Comment by siposdani87** [comment]
The 1.0.0+ version works with Expo SDK48 and react-native 0.71.6
